apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: wac-hospital

labels:
- pairs:
    app.kubernetes.io/part-of: wac-hospital
    app.kubernetes.io/name: pp-ambulance-wl
  includeSelectors: true
  includeTemplates: true

resources:
- ../../../apps/pp-ambulance-ufe
- ../../../apps/pp-ambulance-webapi


components:
- ../../../components/version-release